### ISSUE TITLE
A question about the GitHub program you provided

### ISSUE THREAD

**Issue by 845834089fzj** [RViMLab/TRO2020-CTR-Model-Predictive-Control#1]
Hello,I've read the paper "Autonomous Steering of Concentric Tube Robots via Nonlinear Model Predictive Control" and it's really a nice work. I find that you've provided the corresponding code in github and I want to recode. However, I can't find the CTR_MPC module so that I can't  run it. 
<img width="634" alt="微信截图_20201012202004" src="https://user-images.githubusercontent.com/56429211/102229799-1d226580-3f27-11eb-9863-5173f7034e0d.png">

**Comment by mohsenkhadem1** [comment]
The code is updated now and issues are fixed.

**Comment by 845834089fzj** [comment]
Thanks very much！ I have learnt it&nbsp;for a period of time and&nbsp;no more questions for now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Christos Bergeles"<notifications@github.com&gt;; 
发送时间: 2021年1月28日(星期四) 晚上9:22
收件人: "RViMLab/TRO2020-CTR-Model-Predictive-Control"<TRO2020-CTR-Model-Predictive-Control@noreply.github.com&gt;; 
抄送: "Crazy_Kind"<845834089@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [RViMLab/TRO2020-CTR-Model-Predictive-Control] A question about the GitHub program you provided (#1)





 
Closed #1.

**Comment by 845834089fzj** [comment]
Hi, I can run this code successfully，but I cannot find the time horizon (in paper ,it may means K?) and cannot understand how this system predicts future trajectory(maybe depend on the optimization process?).
I don't konw how the code predict future or optimize ,choose the first action.
Thank you for reading my letter and I am looking forward to your reply!





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "RViMLab/TRO2020-CTR-Model-Predictive-Control"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 凌晨0:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RViMLab/TRO2020-CTR-Model-Predictive-Control] A question about the GitHub program you provided (#1)





 
The code is updated now and issues are fixed.

**Comment by 845834089fzj** [comment]
The example.py script may not use the solve_mpc moudle or the prediction horizon length K?
